[project]
name = "erc721-orchestrated-set"
authors = ["Core NFT Development Team"]
description = "Advanced NFT orchestration platform for creating, minting, and trading unique digital collections"
telemetry = false
requirements = []
[contracts.nft-orchestrator]
path = "contracts/nft-orchestrator.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
